// playgrounds/svelte/src/App.svelte
<script lang='ts'>
  import { defineOverlay } from '@overlastic/svelte'
  import svelteLogo from './assets/svelte.svg'
  import Counter from './lib/Counter.svelte'
  import Modal from './lib/Modal.svelte'
  import viteLogo from '/vite.svg'

  const modal = defineOverlay(Modal, {})
</script>

<main>
  <div>
    <a href='https://vitejs.dev' target='_blank' rel='noreferrer'>
      <img src={viteLogo} class='logo' alt='Vite Logo' />
    </a>
    <a href='https://svelte.dev' target='_blank' rel='noreferrer'>
      <img src={svelteLogo} class='logo svelte' alt='Svelte Logo' />
    </a>
  </div>
  <h1>Vite + Svelte</h1>
  <button on:click={() => modal({ title: '人生处处是美梦' })}>Open Modal</button>
  <div class='card'>
    <Counter />
  </div>

  <p>
    Check out <a href='https://github.com/sveltejs/kit#readme' target='_blank' rel='noreferrer'>SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class='read-the-docs'>
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

// playgrounds/react/src/App.tsx
import { useOverlayInject } from '@overlastic/react'
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import Basic from './components/dBasic'
import './App.css'
import viteLogo from '/vite.svg'

function App() {
  const [count, setCount] = useState(0)

  const openOverlay = useOverlayInject(Basic)

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer noopener">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer noopener">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button type="button" onClick={() => setCount(count => count + 1)}>
          count is
          {' '}
          {count}
        </button>
        <p>
          Edit
          {' '}
          <code>src/App.tsx</code>
          {' '}
          and save to test HMR
        </p>
      </div>
      <p className="read-the-docs" onClick={openOverlay}>
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App
